# Generated by Django 4.2.1 on 2023-08-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(max_length=50, verbose_name='Ürünün Başlığı')),
                ('productDesct', models.TextField(verbose_name='Ürünün Açıklaması')),
                ('productPrice', models.PositiveIntegerField(verbose_name='Ürünün Fiyatı')),
                ('productImg', models.ImageField(upload_to=None, verbose_name='Ürünün Fotoğrafı')),
                ('productColor', models.BooleanField(choices=[('siyah', 'siyah'), ('beyaz', 'beyaz')], max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
