# Generated by Django 4.2.1 on 2023-09-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='productComment',
        ),
    ]
