# Generated by Django 4.2.1 on 2023-09-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_comment_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='productComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.product', verbose_name='Ürün'),
        ),
    ]
