# Generated by Django 4.2.1 on 2023-09-07 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0008_comment_commenttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(verbose_name='adet')),
                ('allprice', models.FloatField(verbose_name='Toplam Fiyat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.product', verbose_name='ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
        ),
    ]
