# Generated by Django 4.2.1 on 2023-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_sepet'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='colorCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ürün kodu'),
        ),
    ]
